[workspace]
resolver = "2"
members = [
    "openssl",
    "openssl-errors",
    "openssl-macros",
    "openssl-sys",
    "systest",
]

[patch.crates-io]
openssl-src = { git = "https://github.com/weihanglo/openssl-src-rs.git", branch = "disable-atomic" }
